[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fourierror"
dynamic = ["version"]
description = "Propagation of uncertainty through a Fourier transform"
readme = "README.md"
license = "MIT"
authors = [
    {name = "Andrew R. McCluskey", email = "andrew.mccluskey@bristol.ac.uk"},
    {name = "Tuguldur Zolzaya", email = "tuguldur.zolzaya@balliol.ox.ac.uk"}
]
maintainers = [
    {name = "Andrew R. McCluskey", email = "andrew.mccluskey@bristol.ac.uk"}
]
requires-python = ">=3.10"
dependencies = [
    'numpy>=2.0.0',
    'scipy>=1.9.3',
    'scipp>=24.8.0'
]

[project.urls]
homepage = "https://github.com/scams-research/fourierror"
documentation = 'https://scams-research.github.io/fourierror'

[tool.hatch.build]
include = ['fourierror']

[tool.hatch.version]
path = "fourierror/__init__.py"

[project.optional-dependencies]
dev = [
    'pytest',
    'pytest-cov',
    'pre-commit'
]

docs = [
    'ipykernel',
    'nbsphinx',
    'sphinx_autodoc_typehints',
    'pydata_sphinx_theme',
    'myst_parser'
]

[tool.coverage.run]
source = ['fourierror']